### ISSUE TITLE
tailwind_palettes hex codes

### ISSUE THREAD

**Issue by sebdalgarno** [willcanniford/ggtailwind#1]
Hi great looking package...exactly what I was looking for. 
I am curious though why your hex codes in tailwind_palettes do not match these on the official site:
https://tailwindcss.com/docs/customizing-colors#default-color-palette

**Comment by willcanniford** [comment]
Hi, glad you found the package! Thanks for raising, they must have updated their colour palette since I saved it last. I'll take a look at updating the colours and then get back to you on here.

**Comment by willcanniford** [comment]
I've updated the package now, let me know how you get on with it! Always happy to have some feedback!
